### PR TITLE
Reorganize settings and reduce duplicate code

### PR DESCRIPTION
**Pull request by Epicpkmn11**
#### What's changed?

Reduce duplicate code:
- *23,536 deletions and there's still quite a lot of duplicate code lol*
- Moves several things shared between most/all themes into Universal
   - Things used in the main code are in the `common` folder
   - tonccpy got its own folder since the bootloaders use it and nothing else
   - nds_loader_arm9 also got its own folder since I left booter_fc and gbapatcher as is, if they can be switched to the main one they probably should, but they seemed more different
- enum-ifies several things
   - no more `ms().theme == 2`! (`ms().theme == TWLSettings::EThemeR4`) I didn't do everything , but for several of the common ones they have enums now instead of magic numbers
- Changes everything to `gnu++17`, I don't think it should make a major difference, but singleton was complaining about being included in pre-C++17 and that seemed to be the most common one so I went with it for everything
- This commit also includes changes to the Emulation/HB settings page, I did that first before deciding to do the code cleanup and when I was done it was a bit late to undo that, I can revert/change it if wanted though

Reorganize settings:
- Settings have been reordered to try prioritize the more common settings, many have also been moved to different pages where it felt more fitting (ex. Language -> GUI settings)
   - See this for a list of the complete new order: https://haste.ピ.コム/iliwofiler.diff (items marked `*` are only sometimes shown)
   - Some things still aren't great, please let me know anything y'all think should change
- `Games and Apps settings` has been renamed to `nds-bootstrap settings`, any non-bootstrap settings have been moved to other pages
- The option to hide a system's ROMs has been removed as it seems rather pointless imo (just put them in a folder) and clutters settings a lot making it hard to tell which options actually have other choices

#### Where have you tested it?

- DSi (K) from Unlanch
- DSi (K) from DSTT
- n2DS XL (U) from Luma

***

#### Pull Request status
- [x] This PR has been tested using the latest version of devkitARM and libnds.

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
This appears to guru meditate when being launched via DSiWarehax. Which is going to be a huge pain in the ass for people who are following https://dsi.cfw.guide

**Comment by NightScript370** [comment]
One change this makes is that the quickmenu cursor position is no longer persistent upon reloads.
It doesn't matter, but it'd worth mentioning.

**Comment by Epicpkmn11** [comment]
Oh that was actually a thing? I figured that wasn't actually saved to the ini before and took it out after I noticed when it caused bugs in the R4 theme (the cursor position was shared between the R4 theme and the quick menu, but the R4 theme didn't save it)

I guess I can add that back if wanted, imo it makes much more sense to just start on the top box though as that's how the original DS did it.

**Comment by lifehackerhansol** [comment]
Yeah nah that isn't necessary. ~~Would anyone other than us notice?~~

**Comment by Masamune3210** [comment]
Probably not, honestly, I didnt even notice it was a thing

**Comment by lifehackerhansol** [comment]
Rebased and fixed merge conflicts.

**Pull request merged**
