### PR TITLE
Add RTL language support

### PR DESCRIPTION
**Pull request by Epicpkmn11**
#### What's changed?

- Adds right to left text support and mirrors some areas when in RTL
- Only checks the hebrew letters since that's the only right to left language with translations at the moment, should be as simple as just adding the other languages characters to the RTL checks to add more, but I don't want to slow printing down more than needed (though supporting the different forms of scripts like Arabic may be hard...)
- I've mirrored settings and dialog boxes and progress bar in the DSi-based themes: (Note: DSi theme hasn't been translated yet and the parts that are translated are just me copy pasting bits from settings/bing translate for testing)
   rtl + flip BMP cheats BMP pgs BMP select BMP progress BMP
- Please let me know if there's anything I should change, I don't read any RTL languages and haven't worked with them before

Other misc things that I just threw in this bc I don't want to open another PR:
- Renamed Norwegian from `Norsk Bokmål` to just `Norsk` as I didn't realize that was a specific variant at the time and I'm not sure which was used. Bokmål seems to be the much more common variant, but I'm not sure which and there aren't both so just `Norsk` is fine
- Adds `UPDATETWLMENU` string to english.ini as it was missing there and thus missing on Crowdin

#### Where have you tested it?

- no$gba, DSi (K) from internal SD and Acekard 2i

*** 
#### Pull Request status
- [x]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.

### CODE REVIEW

**Comment by Epicpkmn11** [comment]
Alright, marked this ready for review as I think it should be good, might be good to wait until the Hebrew translation's a bit more complete and test a bit more though incase I missed anything

**Comment by Epicpkmn11** [comment]
As the Hebrew translation on the DSi theme is 85% done I did a bit more testing and fixed the one problem I saw, everything else looks good to me at least

**Comment by Yola-cola** [comment]
Does this mean the cheat menu is finally readable for long words?

**Comment by Epicpkmn11** [comment]
Honestly long descriptions are probably worse in the RTL layout as you're missing the start of the string instead of the end since they're right aligning, I suppose you could switch ot hebrew to check the end but that's kinda impractical lol

I do plan to try get scrolling working for the cheat names soon™, I'm just not exactly sure how best to go about it so I haven't started yet

**Comment by Yola-cola** [comment]
> Honestly long descriptions are probably worse in the RTL layout as you're missing the start of the string instead of the end since they're right aligning, I suppose you could switch to Hebrew to check the end but that's kinda impractical lol
> 
> I do plan to try get scrolling working for the cheat names soon™, I'm just not exactly sure how best to go about it so I haven't started yet

Understandable

**Pull request merged**
