### PR TITLE
Improve touch and scrolling

### LINKED ISSUE #773: Scrolling and animations in the DSi theme and Quick Menu are a little off
In the DSi theme, touching applets to the left or right of the cursor do not get scrolled towards. 
In addition, although these aren't that big an issue, tapping the DSi theme scrollbar and using the directional pad in the quick menu don't use gliding animations like they do on the official menus and they just snap into place, and ceasing scrolling with the touch screen does not play the cursor sound effect.

### LINKED ISSUE #1494: Add ability to select the icons beside the selected icon by tapping on them, in the dsi theme.
**Is your feature request related to a problem? Please describe.**
In the dsi theme, unlike the og dsi menu, you cant tap on an icon on either side of the selected icon, to select that icon. You have to scroll over to it. 
**Describe the solution you'd like**
The ability to be able to select the icons neighbouring the selected icons to select that new icon. 
**Describe alternatives you've considered**
None. But I guess I could just use forwarders on the dsi firmware if I want.

### PR DESCRIPTION
**Pull request by Epicpkmn11**
#### What's changed?

- Oh god I used to be terrible at coding lol
- Improves my old touch code and several other janky bits of my old code
   - The dragging is still a little weird, but other than that it's basically perfect to the official menu now
   - Also adds tapping on the icons on either side to move to them
- Makes the scrolling smoother
- Also a couple, but I mainly focussed on my bad old code in this
  - Fixes the colon drawing causing a bit of stuttering, couldn't tell before but it was really clear with the smoother scrolling, and also just makes that whole code be less of a complete mess lol
  - Changes `extention()` to `extension()` and makes it take a vector
  - Cleans up the iconTitle.cpp code a bit
- Draft because I need to test it better, if y'all can test let me know if I broke anything
- Fixes #1494
- Improves towards #773, but not quite enough to close

https://user-images.githubusercontent.com/41608708/128693998-a6aecfe3-0f7a-443d-be09-77604b06ea1c.mp4

#### Where have you tested it?

- DSi (K) from Unlaunch

***

#### Pull Request status
- [x] This PR has been tested using the latest version of devkitARM and libnds.

### CODE REVIEW

**Comment by spellboundtriangle** [comment]
That's a lot smoother, almost too smooth!
Though I did notice that when moving a title left/right, the icons on the sides appear incorrectly for a bit:

https://user-images.githubusercontent.com/79382000/128711943-1ad0fba0-3f96-40b6-8cd4-1f05815d7f9e.mp4

In terms of #773, there's also the ability to drag icons using the touchscreen.

**Comment by Jonatan6** [comment]
The scrolling in this patch feels really nice, great job!

I noticed some graphical glitches when slowly switching from one title to another:
https://user-images.githubusercontent.com/66566027/128722841-a6ceaee7-cb05-4bf9-a91a-963b9ef417c2.mp4
I don't think there's besides that (and the issue spellboundtriangle mentioned). If it's of any importance, I tested this on an European DSi with CFW.

**Comment by Epicpkmn11** [comment]
> I noticed some graphical glitches when slowly switching from one title to another:

The official DSi menu actually does that too, though it is smoother so I'll try fix that up

**Comment by Epicpkmn11** [comment]
Alright moving has been improved and somehow that fixed the icons wiggling around. I think that means the spacing might be a pixel or two different from the official menu now but it already wasn't quite the same and this looks better while moving so just going to leave it for now at least. Also improved the dragging momentum and fixed a few bugs with that, it's still a bit weird but better now.

This seems fairly stable so undrafting, but let me know if y'all find any bugs and I'll fix them if I can.

**Pull request merged**
