### PR TITLE
Used english.ini and renamed it to german.ini

### PR DESCRIPTION
**Pull request by malek78i**
Translated into german

#### What's changed?

_Used english.ini and edit it into german._

#### Where have you tested it?

_Tell us where have you tested it._

*** 
#### Pull Request status
- [ ]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.

### CODE REVIEW

**Comment by NightYoshi370** [comment]
Please revert the change made to english.ini
We want to KEEP english.ini but just have the other pages as additions.

**Comment by malek78i** [comment]
Its my first pull request. Hope it's still good

**Comment by malekairmaroc7** [comment]
@NightYoshi370

The file is recreated as "german.ini". "english.ini" is still there.

**Comment by NightYoshi370** [comment]
Now it is cause robz made it in 04d26a2

**Pull request merged**
