### PR TITLE
Created compile.sh for linux

### PR DESCRIPTION
**Pull request by niansa**
#### What's changed?

I added a compile script for the linux builders :-)

#### Where have you tested it?

I didn't, I don't have the devkit installed on this machine. But It **must** work.

*** 
#### Pull Request status
- [ ]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.

### CODE REVIEW

**Comment by eku** [comment]
@niansa please run [ShellCheck](https://github.com/koalaman/shellcheck) on your code.

**Comment by NightYoshi370** [comment]
`make package` does exactly this and it'd stay up to date.

**Comment by niansa** [comment]
oh, okay

**Comment by urmum-69** [comment]
then... what's the purpose of the compile.bat?

**Pull request closed without merging**
