### PR TITLE
Remove Chinese/Korean bundled fonts, load Default as a fallback

### PR DESCRIPTION
**Pull request by Epicpkmn11**
#### What's changed?

<details><summary>old description</summary>

- Switches the bundled Chinese (Simplifed) font to @CaiMiao's WenQuanYi Bitmap Song as it's much smaller
- Removes the bundled Korean DSi fonts as they're the same things as the Default DSi fonts and adds the defaults to always be a fallback

</details>

- Removes Chinese and Korean fonts, just the "Default" font is bundled now and the rest can be downloaded from twlmenu-extras
- Makes it try the Default font as a fallback, the Korean font had expanded Hangul in DS mode but was identical in DSi mode so it saves some space
#### Where have you tested it?

- DSi (K) from Unlaunch and DSTT

***

#### Pull Request status
- [x] This PR has been tested using the latest version of devkitARM and libnds.

### CODE REVIEW

**Comment by Epicpkmn11** [comment]
I added the old "Chinese (Simplifed)" font to twlmenu-extras so it can still be downloaded from there, I/anyone by PR can add others too if wanted.

**Comment by Epicpkmn11** [comment]
Actually might be better to just only bundle Default and move everything else to twlmenu-extras, what do y'all think?

**Comment by lifehackerhansol** [comment]
Think having just default is fine.

**Comment by Epicpkmn11** [comment]
Alright moved the extra fonts to twlmenu-extras so this PR is just remove the all extra fonts now, should save a good couple MB in the 7Zs.

Side note: I wasn't sure exactly what to put for WenQuanYi in twlmenu extras so I did `WenQuanYi Bitmap Song` for the title and `Qianqian Fang` for the author as that's who Wikipedia says the author of the font is, let me know if I should change anything.

**Pull request merged**
