### PR TITLE
DSi-based themes: Rework text rendering

### LINKED ISSUE #999: Word Wrapping on game titles
**Is your feature request related to a problem? Please describe.**
With certain games my rom file names are verbose and sometimes go off the screen to the point where it is difficult to tell the what game is selected. This is probably specific to the DSi theme, but it still could be an option nonetheless

**Describe the solution you'd like**
Just a simple setting for making the text wrap around into the white space instead of being centered.

**Describe alternatives you've considered**
Maybe a choice for a smaller font, but that might be harder to do

This is with v14.0.0 with the DSi Theme, on a DSi XL

### PR DESCRIPTION
**Pull request by Epicpkmn11**
##### General:
- The text rendering has been nearly completely reworked to allow for support for larger fonts with Kanji and/or Hangul and custom fonts in themes
  - Note: The default fonts currently do not support Hangul, it would be very easy to add though
- I've translated what's translatable of the DSi theme to Japanese (with Kanji!)
- Fixed long words (without spaces) not rendering correctly in cheat descriptions
- Long names in the file browser will wrap lines on a space if found otherwise in the middle
  - Fixes #999

##### Printing syntax changes:
- Instead of `printSmallCentered` and `printSmallRightAlign` (and large variants) functions you now optionally pass `Alignment::center` or `Alignment::right` to the `printSmall`/`printLarge` functions
- `Alignment::center` prints will automatically detect line breaks and center each line correctly so you don't need multiple strings and print statements
  - Note: I didn't change anything besides the cheat comments to make use of this
- In `Alignment::left` the `x` value is the leftmost pixel, in `Alignment::right` the `x` value is the rightmost pixel, in `Alignment::center` the `x` value is the offset from the center of the screen to center the string on
  - An `x` of `-80` would center the string on 80 pixels left of the center of the screen
- Switched to `std::string_view` instead of `cont char *` so you no longer need to use `.c_str()` when printing a `std::string`
   - I removed the .c_str() from most/all of the existing prints
  - `std::u16string_view` is also printable so UTF-16 text can now be printed without needing to convert to UTF-8 and back (specifically useful for the DS titles)
- Added functions in fontHandler to get the height of the small and large fonts

##### Themes:
- In `[theme]/font/` you can place `large.nftr` and `small.nftr` for the two fonts
- In `[theme]/theme.ini` you can specify the palette to use like:
  ```ini
  FontPalette1		= 0x0000
  FontPalette2		= 0xDEF7
  FontPalette3		= 0xC631
  FontPalette4		= 0xA108
  ```

##### Known bugs / regressions (tonccpy - Current commit)
- [Regression] The cheat menu now shows fewer items, this requires slower printing or cutting off part of the text to fix
  - If using a shorter font more items will be displayed, it shows as many rows as can fit in 96 pixels
- [Regression] In DS mode there is some minor flickering when pressing a button when a long game file name is being displayed in the per game settings window.
- Edit: Happens in master too
  ~~[Bug] In DS mode sometimes the audio will corrupt when moving beyond the last game, it sometimes fixes itself when going back and forth between games and empty slots. This is most likely caused by having to draw text and the background image in the same frame~~
<details>
<summary><strong>Known bugs / regressions (DMA - 9b8d0aaaeca13feaaaa77248d36d41d07aa3b81a (see above for the current commit))</strong>
</summary>

- [Regression] The cheat menu now shows fewer items, this requires slower printing or cutting off part of the text to fix
  - If using a shorter font more items will be displayed, it shows as many rows as can fit in 96 pixels
- [Regression] The text drawing is still a bit slower so in the cheat menu when showing lots of very long titles the text will flicker when scrolling. In DS mode there is also *very minor* flickering when a long game file name is being displayed in the per game settings window.
- [Bug] In DS mode sometimes the audio will corrupt when moving beyond the last game, it sometimes fixes itself when going back and forth between games and empty slots. This is most likely caused by having to draw text and the background image in the same frame~~
- [Bug] Text in odd columns will be 1px left or right, I haven't figured out a way to fix this while using DMA, but I'll try switching back to tonccpy and see if that's still too slow with my other speed improvements

</details>

#### Where have you tested it?

- DSi (K)
- DS Lite (J) with DSTT

*** 
#### Pull Request status
- [x]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.

### CODE REVIEW

**Comment by R-YaTian** [comment]
Will the default font support Chinese?

**Comment by chyyran** [comment]
You can extract a `TBF1_banner_lm.NFTR` that is the perfect size, the large NFTR is a little too big.

**Comment by Epicpkmn11** [comment]
Oh, hadn't been checking on this...
> Will the default font support Chinese?

Currently there's probably a bunch missing as I'm using the Japanese fonts, but it would be easy to add the needed characters

> You can extract a `TBF1_banner_lm.NFTR` from the DSi browser that is the perfect size, the large NFTR is a little too big.

I think I'm using a banner lm size font as of 6df4efc, but one generated from the 3DS font instead of the browser one

**Comment by Epicpkmn11** [comment]
Hmm, master actually does flicker on the file browse titles while this doesn't so the speed really isn't *too bad*... I think really the only *big* problem with this is that letters starting on odd pixels (I think? I forget the exact cause) look slightly weird... I can't figure out how to fix that using DMA though and not using DMA is way too slow...

**Comment by chyyran** [comment]
The 3DS font is just as good if not better :+1:

**Comment by RocketRobz** [comment]
Hmm, the latest commit doesn't seem to work on original DS consoles now.

**Comment by Epicpkmn11** [comment]
> Hmm, the latest commit doesn't seem to work on original DS consoles now.

Huh, it works for me on my original DS and DS Lite from my DSTT...  [here's my build if you want to try it](https://github.com/DS-Homebrew/TWiLightMenu/files/4714521/dsimenu.srldr.zip)

**Comment by RocketRobz** [comment]
> Huh, it works for me on my original DS and DS Lite from my DSTT... here's my build if you want to try it

Same issue. It restarts TWiLight Menu++, instead of showing the ROM menu.
Could it be because of the theme files I'm using?

**Comment by Epicpkmn11** [comment]
> Same issue. It restarts TWiLight Menu++, instead of showing the ROM menu.
Could it be because of the theme files I'm using?

I tried an old theme and old everything except the `dsimenu.srldr` and it all works... It used to crash for me the first time I tried but somehow works recently so maybe there is something weird having an affect on it...

I'm launching it YSMenu -> BOOT.NDS (flashcard) fyi

**Comment by Epicpkmn11** [comment]
Update: Robz tested the latest commit and confirmed it is working on his flashcard so it was a RAM issue (tbh I'm kinda surprised it worked with those huge fonts at all in DS mode), I also tested and the audio bug seems to happen in master too with similar frequency so that's unrelated to this PR. The only real regression is the cheat menu showing less items, which can't easily be fixed, but its not that much worse and imo kinda looks nicer.

If that's all good then I think this should be good to merge unless some other people want to test it first. ([Here's a build](https://cdn.discordapp.com/attachments/489307733074640926/720068337039573012/dsimenu.srldr))

(Its just 6 instead of 8 rows):
HNI_0002

**Comment by R-YaTian** [comment]
Still waiting for Chinese characters and Hangul support :p

**Comment by Epicpkmn11** [comment]
> Still waiting for Chinese characters and Hangul support :p

I'll add the characters as needed since having the large amounts of unused characters uses a lot RAM that was causing it to not boot in DS mode on some flashcards, so once there's a Chinese / Korean translation (and if more Kanji are used for Japanese) I'll just update the font as needed with only the needed characters.

**Comment by R-YaTian** [comment]
> > Still waiting for Chinese characters and Hangul support :p
> 
> I'll add the characters as needed since having the large amounts of unused characters uses a lot RAM that was causing it to not boot in DS mode on some flashcards, so once there's a Chinese / Korean translation (and if more Kanji are used for Japanese) I'll just update the font as needed with only the needed characters.

Oh, it's a good idea. But we should also add some characters that ique/Korean games' title used, hmm.

**Comment by Epicpkmn11** [comment]
> > > Still waiting for Chinese characters and Hangul support :p
> > 
> > 
> > I'll add the characters as needed since having the large amounts of unused characters uses a lot RAM that was causing it to not boot in DS mode on some flashcards, so once there's a Chinese / Korean translation (and if more Kanji are used for Japanese) I'll just update the font as needed with only the needed characters.
> 
> Oh, it's a good idea. But we should also add some characters that ique/Korean games' title used, hmm.

Yeah, I'll just need a list of every iQue and Korean game's titles as displayed on the menu and I can add those. (I'll probably look that up in a bit if no one else happens to have that)

**Pull request merged**
