### PR TITLE
Update language.ini

### PR DESCRIPTION
**Pull request by chronoss09**
#### Where have you tested it?

***

#### Pull Request status
- [ ] This PR has been tested using the latest version of devkitARM and libnds.

### CODE REVIEW

**Comment by RocketRobz** [comment]
Is this change implemented in Crowdin?

**Comment by chronoss09** [comment]
i have no link for Crowdin

**Comment by RocketRobz** [comment]
> i have no link for Crowdin

Here's the link then: https://crowdin.com/project/TwilightMenu

**Comment by chronoss09** [comment]
> > i have no link for Crowdin
> 
> Here's the link then: https://crowdin.com/project/TwilightMenu

Ok, i will added my fixe

**Comment by chronoss09** [comment]
> > i have no link for Crowdin
> 
> Here's the link then: https://crowdin.com/project/TwilightMenu

Fixed

**Comment by lifehackerhansol** [comment]
The fixes were added in 4895c476910536883294dd72b97bbe6ae7d1a95e

**Pull request closed without merging**
