### PR TITLE
Show warning when enabling cheats with E codes

### PR DESCRIPTION
**Pull request by Epicpkmn11**
#### What's changed?

This makes it show
> This cheat uses E type codes
> and may not work or cause
> the game to not launch.
>
> (A) OK

when enabling cheats with E type codes. I don't really use cheats much ~~yet I'm the one that added the menu~~ so I'm not sure if A) this even checks correctly or B) those are the correct symptoms of E type codes, so I'm making this a draft until someone can confirm that.

It does show on the `Screen Swap` MKDS code which I know doesn't work and I think is due to E codes and doesn't show on some other ones I know work so it might be good, I'd like someone who actually knows to confirm though ;P

#### Where have you tested it?

- DSi (K) from internal SD

*** 
#### Pull Request status
- [x]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.

### CODE REVIEW

**Comment by NightYoshi370** [comment]
Please make this only activate when Heap Shrink is not set to either off or High. Both of those environments have working heap shrinks

**Comment by Epicpkmn11** [comment]
Oh, missed your reply, isn't Low heap shink getting removed now? So is there even a need for this anymore?

**Comment by RocketRobz** [comment]
There are still cheats that aren't working, so I'd say keep the warning.

**Comment by Epicpkmn11** [comment]
Ah, I'll try get it to be more accurate to which are likely to not work soon then

**Comment by NightScript370** [comment]
Can anyone actually test if E-type cheats are broken in nds-bootstrap? I thought this got fixed.

**Comment by Epicpkmn11** [comment]
> Can anyone actually test if E-type cheats are broken in nds-bootstrap? I thought this got fixed.

I think it was mostly fixed, but there are still a few that don't work. I haven't seen much if any complaints about broken cheats recently though so maybe it is good. I think the bigger problem is DSi mode cheats now, cheats are pretty broken in DSi mode still I think.

Since I don't think anything about this is really accurate anymore I'm just going to close it.

**Pull request closed without merging**
